apiVersion: v1
kind: Service
metadata:
  name: reactive-resume-postgres
  namespace: reactive-resume
  labels:
    app.kubernetes.io/name: reactive-resume-postgres
    app.kubernetes.io/component: database
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    app.kubernetes.io/name: reactive-resume-postgres
