apiVersion: v1
kind: Service
metadata:
  name: reactive-resume-printer
  namespace: reactive-resume
  labels:
    app.kubernetes.io/name: reactive-resume-printer
    app.kubernetes.io/component: printer
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: reactive-resume-printer
