---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: reactive-resume-secrets
  namespace: reactive-resume
spec:
  encryptedData:
    AUTH_SECRET: AgAnimgGbWi+IBouf30j1vaUClv8OHlfZFWdmy7sx+YTb0vw0orP8YtdFNMoghYujn/we3SesmimUFASorQyeNF5I4UqIs44655zWlVtZl6qpSN434vsD4XYr/BVADLI430Kuetp5b8G738D1fwPSo3W93q+hehqj7Jjbd+5N0ZmbwL6zWxkT7h09IMA1DhmAglX20XEl+RPuY3NaFDTuKCpVgaKbNSTfUtobkM/aHJMk0NhGL4jvidK5WTDSxZZI8eQYJFDLL+qujhXrHMhGuKYtJ1HQmZmf/tthnEDA1X3ZTAFWn7RtQDVwMMSmm9dw2goDLcrXndu/juXIAPxkmm2YcDFVwfzSxzKZ/jB3OELvR1Rl6f+i1actAcO2Y+5EtLtEswsADksRxox/uZa7FOtTeqUbXl3Z9hV95MZUwO5u4wNDHIGspAnQvh++fNPFwokuhpptRset1umK9QKsHveeyecP6nnrb6nTu++pNcZe24p5OunLErz26Kw4KYN+5OHgBdQnl93NFdvqrxDcW3Bb8sr5MoVKXNU6uGUC04HXATVKobWB2KZ/F3yFsGcWFpQpXpLkizRi9/yb++sm69MwJ43u4Gat9Jwo1Bfyocm8ZjooNBSy2T91Z3SskSAkpDq6bvnyki0TxKvyU7+hftOJnL6RsV6CH7/0xuPFFlTgdjK9EzVhKT5/fE8l0F9xeOzulBX16WX+zMpiI5uMfTSZkpilzka1uzN7+wpikZ4sc6a9ZHWPbV8Q/Bghffc2xAp30F6+F0ZTjew6W84BCUC
    POSTGRES_PASSWORD: AgB89QpQ0df6qWgvIz2xzbrrYjuXLyjFWg0Dl6mk6nIoFrGcVDHGnEf2Dy/JctHY1uMfbjAnBaPcF3Xmasl3CMUh+uzr6NhdFA4grPOhGfESV9Tv/QpO5Psgx9Ebx2BLPvIG/AhsGaMiVDRCEA5KWYgwlpG46tFHc92++3bSMewNGv5HxZ+nVkN5AyQA0kbu3WCZRyjePexDnxL2BhjGMaAvLudUXOpr43bXdfDPiPsv90kSvtePxm5P1sIUVyNUxZD8riefM6EVVgof2OsGYJSLQMKuPxvUpoE6Z8X/wje3vc1pet78kHr1rl/MyZVkM6mH/R+WquPv16jTXWYgLS6JbP1lCAKKawAMwApjjwq7/mAc2fkBn3belt+B7vKWyP0rnKazXztXZT4KlsKA1QoMGl5SnojtptmBdqLYhMT+krhIzR+rxiuYSdJSKL2h+cD5khtkDFdoHp03ubJObKwhlrcyGMrQw8/sM/epfN/nL0MaVRhVmCrsac1xeHicu7wm3IT8yRoqe0AeGFZtgRhETYXDMl+GIaHhj8s1BUGle4SWp6adnoUc0+OkBXLGv2tEah0hSBQvam5H+oKC7qTiVgkUGzGJG82NmK+PpaCn6m0Cc5pEQLtGDLGbyt9q3zlf1xC3kM13f0aqOQFOKmSwCbyuJNqc3bQOxjZ/y1BxeOc5uE+Wybj48WuJD1QD3xzGHKz+mbtLCCT/08g4vGYv5gWLkIsHjvsoI9jZdevpUA==
  template:
    metadata:
      creationTimestamp: null
      name: reactive-resume-secrets
      namespace: reactive-resume
