apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spacedrive-data
  namespace: spacedrive
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 50Gi
