apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spacedrive-data
  namespace: spacedrive
  annotations:
    numberOfReplicas: "2"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 50Gi
