---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: spacedrive-auth
  namespace: spacedrive
spec:
  encryptedData:
    SD_AUTH: AgAevinzrdEHq3lnZNLM93q95e5meS5HhO0FJRRkOVG/9WfX2Ur2pK1BcHxdQAK/In6llm3rprOkVs7PlqtTvDE+U8EutiGb3w/8L2ogpEol8t1FB5CyXKD+vNVU5qySanXZgqNNpvzm55RJKf50bcUA8cZVzWkDEasa25X6JWud7hmwM7sSO7689/MtsxsIsJfv6aNqW+8ABWRO5huefZWBPJouP8x3wNwbwS1PySvdYoJASEiYsciXe8RIWCdn5QghsykOc0TTMQb05T/RLsmqmDhT7qZCWyuVq9pGi4Uq0z5+XPryCzyMSpLK0bUsSULx57tPnP9BpeCBhl4HLIa6QdWkkvqyUcSVh/YFVV+pwzBk/VSmd4xNtDZ1l18rK6k6HX1hsyik8+DiDb4OGHa6b/U79usPh2NjKskSEYBonp42I9jxr35Jc695hz2rM9Bmqcuuz7yQjY/QgBmjRMaeFAc7qL3G2ClxljCHN4NgUxIueKr9K1RqYeEeMbeaLcPf24gIt450rmc7lNWxaYzCcKlic7Zeta0QHBmISfED2FzP+8V038fnHLlrh47/2tOlmbFsYP1Klq85ooS6iZkn3IkZvx7Odk6uAfcg9R5UhfnWPQGW6g6SgsgN/8yazBR96k9ZyQZETLF8EdkirPOCO9dMWkQTW0xrKLVYFEjMzscrWl8DchK5wrflbl14mEoO0OXAvYQrzm2m8X9i+dR8640DlVZLgHmeop5Lk7xcLMA0pKxpJN0Nga/Rfu0wjbOu
  template:
    metadata:
      name: spacedrive-auth
      namespace: spacedrive
