  - name: Home
    slug: ""
    columns:
      - size: small
        widgets:
          - type: calendar
            first-day-of-week: sunday

          - type: weather
            location: 29615
            units: imperial
            hour-format: 12h

      - size: full
        widgets:
          - type: monitor
            title: Applications
            cache: 1m
            sites:
              - title: Linkwarden
                url: https://linkwarden.nicholasshaw.cloud
                icon: sh:linkwarden
              - title: Spacedrive
                url: https://spacedrive.nicholasshaw.cloud
                icon: sh:spacedrive
              - title: Reactive Resume
                url: https://resume.nicholasshaw.cloud/dashboard/resumes
                icon: sh:reactiveresume
              - title: Open WebUI
                url: https://openwebui.nicholasshaw.cloud
                icon: sh:open-webui
              - title: Stoat
                url: https://stoat.nicholasshaw.cloud
                icon: sh:revolt

          - type: monitor
            title: Infrastructure
            cache: 1m
            sites:
              - title: ArgoCD
                url: https://argocd.nicholasshaw.cloud
                icon: sh:argocd
              - title: Longhorn
                url: https://longhorn.nicholasshaw.cloud
                icon: sh:longhorn
              - title: Netbird
                url: https://netbird.nicholasshaw.cloud
                icon: sh:netbird
              - title: Prometheus
                url: https://prometheus.nicholasshaw.cloud
                icon: sh:prometheus
              - title: Grafana
                url: https://grafana.nicholasshaw.cloud
                icon: sh:grafana

          - type: split-column
            widgets:
              - type: group
                title: Reddit
                widgets:
                  - type: reddit
                    title: r/selfhosted
                    subreddit: selfhosted
                    show-thumbnails: false
                    collapse-after: 5
                    limit: 10
                  - type: reddit
                    title: r/homelab
                    subreddit: homelab
                    show-thumbnails: false
                    collapse-after: 5
                    limit: 10

              - type: group
                title: RSS
                widgets:
                  - type: rss
                    title: EFF
                    limit: 10
                    collapse-after: 5
                    feeds:
                      - url: https://www.eff.org/rss/updates.xml
                  - type: rss
                    title: MIT Tech Review
                    limit: 10
                    collapse-after: 5
                    feeds:
                      - url: https://www.technologyreview.com/feed/
                  - type: rss
                    title: NPR
                    limit: 10
                    collapse-after: 5
                    feeds:
                      - url: http://www.npr.org/rss/rss.php?id=1001
                  - type: rss
                    title: Wired
                    limit: 10
                    collapse-after: 5
                    feeds:
                      - url: http://feeds.wired.com/wired/index
