---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: openclaw-discord-secret
  namespace: openclaw
spec:
  encryptedData:
    DISCORD_BOT_TOKEN: AgCds0rfRwZm92uWKhBtnjCPZOwH00WlmMvbaz4hkXkhT2JPOKmYYPHAlYIRZreLBiM/YSX5vXNdN/ClC43WLNz3lOD47RAC2mteXgZWe6uI8rxf9k/i5Mx5pJ1Ft378X7RENl5JyYfqdoAo6xwLBT2A7KfdynzSlTYo6eaQpaHjkdbLwRDNf8hAuYWmaz8UcSeHKXLtVjWFsOUGitDthi+C3rjyxDx6d59DPvMtZ5BsfCErSLU+gb29cdwQtyNk5ZlkYn3vHnFyZdqiay9YTXgkkVAlHxD+KP2ttoYw8w1W8PTjAWoE0acWhqDWAqOp57sizImyfdQNqNfTaDUjFdMPxrqefsiN3zqYytucgDm7gxYfZcseauskCtFLDncVB5lmqy61QlxqwmpY0j2eKV/Nxb4DezYgBzsAlwzLpiaK/ekhREJYUyTLIkLqD2SdzJLK6e9+98plcJSQ7Nt6qa3sSIeo+au32daJ5QD2wjb7gwl9NfyWGMGXPE5ari6KjMhUm8crm/6ylvbZ/VYd2MDJWrFYzXNXcKI+a50TViSjvVMM7ur9nSSfJDOrMDcEFK1DAmDJIkDAZoUmTV1Zb9lFZ2uY67+rQbDri5tVdgZ/CW618ZFtLAfzNyiOqA2SltdEl4gKmf+Z1Rq6+YdY1gM75EJYje4KHOXqDSiHFVOl12HZRx4YND6lIbqlqe5ZNZ8j7HvUFj1iX+P9tpB2wz/10LPPjuhHhrzAYEbiuMgLeb+hkGlqi3l1CEFDkN0dslg0IB/fWSYf22JqB5oCt7m4vpAwhBLQ3ts=
  template:
    metadata:
      name: openclaw-discord-secret
      namespace: openclaw
