---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: openclaw-secrets
  namespace: openclaw
spec:
  encryptedData:
    OPENCLAW_GATEWAY_TOKEN: AgCYJiUPP6R0JQAn3D11vsQsOaYYIxU1TXCG+JC16QYjQXaF9nqMNeNreRU5me8rrs33F908bdPRYctzWDHqp5+cMWmMb2GTXxxGqTs7WC1Q+yEdEmPoOUjOgJNyqfy22I04isi+4IQtbQ296QVLVhvX4yDU7wRwmgDiZL/VnEUDp8Kjv6vuLaFfRaQZTrZHRZRQgWwiPJHhgjMtQJL8vrWBBFIwhFe7TnCff3+7HTZkDVRrrZjBpPWWwC9bcgMt11Ed91TpVW6tC3oAlZ46HG4r7TxCCRXmyWtzc7/yfdmsbbF6xE9jVM2O6GtcOanGnLw5VXdBRGD7eIAzU8cpVfLAv7A8yhQR9tXnyFuYwi8tk4MqwENAK+GUrmydR8Ig3aT3QLYnHj/bkUJkqF7n3OKLQBtrY54qdrIKzZZios8hEKmXoml1HVAjvXKSEwYUXGck9CMMsct2BQ0EFwBRUuJevRkDhN9RNH0TPEkuqFTUCHn6aTGBVv91MBO7GDXkkq1tByCfo7wHM8iNUU3R3FxKscsATPH2yhXY69btUynB+ag2dXEx620bCbQ/FBA6KB/xz/VqBHk2jWmIs5Bp6YWSUnUM+HPN0rHDiE1q16NENwXouHiRBMFzlYciaMuNk1gLF3q4Pp5jo5kZzcPiAcZ+MwQoYoxdxFy1AZDURpsAtTuhgXEeIGpZS+q/9zEGC++vCaMPqM0iXeTrcSJAnD4G3rWN21+yu5d7+tZ1fz6g4bYFJ6OsCrdrqNCfYOnYlYNkQOXeeZ0qcMGmMelaVF9c
  template:
    metadata:
      name: openclaw-secrets
      namespace: openclaw
