apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.longhorn.io
    chart: longhorn
    targetRevision: 1.8.1
    helm:
      values: |
        preUpgradeChecker:
          jobEnabled: false
        defaultSettings:
          defaultReplicaCount: 2
          createDefaultDiskLabeledNodes: true
        persistence:
          defaultClassReplicaCount: 2
        ingress:
          enabled: true
          host: longhorn.homelab.local
          ingressClassName: traefik
          annotations:
            traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
