apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
  annotations:
    argocd.argoproj.io/compare-options: ServerSideDiff=true
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.longhorn.io
    chart: longhorn
    targetRevision: 1.11.0
    helm:
      values: |
        preUpgradeChecker:
          jobEnabled: false
        defaultSettings:
          defaultReplicaCount: 1
          createDefaultDiskLabeledNodes: true
        persistence:
          defaultClassReplicaCount: 1
        ingress:
          enabled: true
          host: longhorn.nicholasshaw.cloud
          ingressClassName: traefik
          tls: true
          tlsSecret: nicholasshaw-cloud-wildcard-tls
          annotations:
            traefik.ingress.kubernetes.io/router.entrypoints: websecure
            traefik.ingress.kubernetes.io/router.tls: "true"
            traefik.ingress.kubernetes.io/router.middlewares: kube-system-security-headers@kubernetescrd,kube-system-rate-limit@kubernetescrd
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
      - SkipDryRunOnMissingResource=true
