---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: karakeep
  namespace: karakeep
spec:
  encryptedData:
    NEXTAUTH_SECRET: AgBwOkwYds5rX7pzg7+nYMaLPeYRTmQG1hCwIM0hHvJDVb9f7Dxfut0nvm4aOtA6YYtrRwH2GgS2rWqNAjlDmXsLw/LT0LBxXPh2+0XVJPuoUcyh8Dj5PdOOnT9bM8xzWLtn6/qE7dVmIEZ5AK3WctG8lcjCb92ZVA7NJLiTeLulOS1NmHB5tUN5NyOcVWZ5amJIFevRgkxINjEFZZhiK2+ROYuFsC8o1TiTkPILcH570WapRqfGdtK0txmzd40VgkaPFZyxj7rv8NDPkYKfpdqZIH8cbuTfD0kmV0By9rtPqcKnrzlR3ClZWoGRqcPyUKib1yH3ByEhq+LNnpjamfjIb2UIFnm2nmR/Lz5hy58Vzc5Tn96vxl3Lw2nsdfbCB5m211fkGAZ9Nq6RR4js5FfdVLIxIbIoOkuHSuQKxDT7yzS9lrceW/tAiXoQSfIGM7YS151pnHqhMbf98NcTrgfqvOzaLSZiJ964MY2S48VkhfetwVy7uh8jYwxM017VWsgm0vx3H51MkefKTIzcNny0rT4AYwID6TCGR2KQ6UJW6Bs7sTQcMHwPwnzSxAxlpBxACt95vEGpYrIer2frcO0bW9XNQ4qrIpYqY0f5YnIAGDspIgJfWJt2mb9PHGA45HQ0Z8mTyCI5oGnw8Kk0fW86eAfmPzB6qWWfxCt4IQeKlqm8/7nNdP2WM65SB58LddvyvG1z5+bxbzNsKvJKMyOMJDKKggSllqn0+oq0tqF4cea2yM8n2AykP+y+tx7bcnM=
  template:
    metadata:
      name: karakeep
      namespace: karakeep
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: karakeep-meilesearch
  namespace: karakeep
spec:
  encryptedData:
    MEILI_MASTER_KEY: AgBeyQulULw4tm1EUlx0P7aK/kHUuEHnxRMNBT98YGcvfVVEpfOQkTy+MsCdloQuKVKsFTBS9wbxMFp8xdKNyETTIb11mYL/VrWmyVUCyf7LRDKhkWiSNg2mLCla9jo/BJAH+rOLpvEmVBkqjaRo6pDl6Se/QC1s9yOUcpd3rKSiU9fpTqljYPE7GyVUlKynYhS4bPbf6wsc+8PJrHXScQhUcM6jXTqY07fLPeuKivU7JEom/0RxlG//dj6E9E7ORJac8OguoWu7AFWa5FJ+Cv035xkmgdole1NfOVMv44g4cK9my/sRkLTjXo9TbCjMGcttzhZW3xmg28Y5K/ossS1UGHwI3Fygxb2L6P81BRQchmUGg9nFijHXDScF2dysPcx6rxzcVQJvAaWkDUZ3kuFdidxnowojnzSOUOVBEK/ccH6R55casdSOTXQN+G12Aj3xUqNh0nmRL3x0Rr5hR9E5pZv/grtvMn5H6wGgIE4BNVmEYdBK0iQkzJuQTFWOv5GDo04VMXHbIsJiRvW5J6mCUcwrigC/FRSk5szHps75GIZpxzKCi4iOcvq4RKeJgCqpR3oK53DOwv1MIXEK4C6VTN5CmYiE56x7EoamSavDC79sLTOjAlAjFKcl7nFYtfhlzsrbwaViFaW8luKKdLx3/dwi8X95Uf1ybixDBeUKW3d0Gjym00Ep1e5vAMGrqQwVn2iWginem2XKt9ZtNnTudWjA51MDiFbcKbw9nbA=
  template:
    metadata:
      name: karakeep-meilesearch
      namespace: karakeep
