---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: renovate-secrets
  namespace: renovate
spec:
  encryptedData:
    RENOVATE_TOKEN: AgCx0hHA2GRNTPyS+oWMoSMdqidK64Fwd+IXOXLiQ9wbtQg748/oKO9xy+ikPd3xDQg0EH5epAqkO+Bnx+gq9UYLQIAGfT6jA8Gh8x0jAi07F3/+6c0eb0JPJ/A+TrPe7x9m1ItPFd0sE53L7+pJZQQcQ+mB/4gpdxXlyJCV3UrVakMw+4aoO4njjn5IM6NgTdcjzxmcWCULgBPYeARnwZgeUXX2z+X4j4Ad+YUZgbOBQOZSWFDu8PeZbh01MqV6fzJqPSz0YOvw2lbfYar6+MrsgVZHzioGTGt2ZWpAHKf8qztVuIMWmStxaH51WY1FY4oP2SL4fXXDfNzSoxRb05vzgQk9+1urGVMtMqPkVT0PuQiq0LeT02legu8o/01dafj7AGmtL6Hkasp+Awem+7H6TNLPsew3UwiLNKQBbHtQr9/foDk5xxm9xa1+hvlS5/ome6N2d1i7AC2/I1TwlP3PWm5A+Bpx6e3yA7mJy1/kJm3Luc3x2e2a3UF3+RihCFb2KCZxMFXy3gOiiFIVpo3JQoPBMs5h0jQjru2eDotp9U503kH0BFHJyObkxoAWbiPvRUyffWmMnl4BcG9npxWk1nI5Ckl/tc4/NCuVbOJ4JTkW1MRakKKLCYf2pTkPtdD4sFtMFxREF9V0Q6+7s8Of+IFLh3ogyaFUQnjLe+oqq7XEEXmkD+q/k0G76fIKJUNXSFaPqjrPtZ5LI8JcnH8dIiyPnEjudZ72xd5HP3kUdRWVu6fT/r1Y9QBS6kietzmY9GIMPJpXXrshO62YNwuEtkgOnwWacbP/KZoecwiMAP+9Pj5yh3OckDV0r8A=
  template:
    metadata:
      name: renovate-secrets
      namespace: renovate
