---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: renovate-secrets
  namespace: renovate
spec:
  encryptedData:
    RENOVATE_TOKEN: AgBqcqBq5ZYlOtnGUV9/xq6uMEIGEhaGpz+IR1u8/lGBc+C+f1LcMG2t3F+Cj6VeHqX2xSr+4oWOGInHJLUITr/E4t7n9+glwAYViEtsFmn2PL5MNL8nDhrGHEnb2AWXdbR1EXNNpdxNhJ9a6aPXRpS/w+3N91JnkPjCRNkMsMRYXuRoqHopP23YxbS1bG+RXrAX2qAV0ZPkOq2TBqhzz45M+uUvffSipZaLdIB6uWaE+fWP4d3w8NZq/yXbR866RTO9QEX6yPXlcetUtjR/IYg+8jG2fG7XWmbqlSsc/NWJndyQ5lqFS1JYdHrOg3B/+2wYz5clCj/RnFif3La16QU46IPFLb06T054xPGUeowoM9zSTUeD6dwRYw+x2WPBh6hJTndBolkhAsW0pjqbl4irBUAVwpkpLM0WsxGl/erg1xcdGq0UOZrslA4XyvNDT+7JBmIX9r1nyNDMyGjsMABzVY0bzNnLLb/2TnevuP0XW48A4tFZK6JC/sm5xSlmccbKgSlB1uN0I+/ApCWALLlknwetQrcCQjwSmdJWJ1RsSVyDHgKo74MzXQoy2cvEJlEyUAiFvooFDcogsnwPePMZ2Md0m1s3jskYW9939XEuR0mev0Uanwfo+o3uxJMAVhUvX7PiyMppDhVwZUVYavaHdw5bGknF6EwNG+OVZmszqF5fz0De36C+zulGBcTTLSv62cOTm9+6aYmh7K2XJ/xHo4lu7U0WqCdyEsYlIbqkOXNoi6AKqBZc
  template:
    metadata:
      name: renovate-secrets
      namespace: renovate
