---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: immich-secrets
  namespace: immich
spec:
  encryptedData:
    DB_PASSWORD: AgABJ7DNoAoKi9arHv/Vmud+iJghKMM6GXbekvK9KrgCjx6sBmOL0W3FHhZhO5vI0Q2uCQvgo4fukDsvmI3p4b04VUahJ5SIUEO+DzkE/O0XkVaK5UPwqwTU9D9nGq/rnjXKtH8Da5JU/J05iMgVcvgfeefLH9lUcVwT4Kd4ycJoxEleP6N/VXwm60YZvZjmVcelewagnFjiwJNVFOHNnC3n1fwcCK9BBbkVDsykzldLajQ261YyZtYQNd2N0HB+dPijPRsEC9Hey9ynJV4tx2rPeXtcbB0cdhgu9K9YD99kN+L6Eq9dI2ji9FdLNlRIf6auKEdUt0dYcmRZFKdkVmGAFAvPOJNEFu9AovTQ5tMFbjWXX344HzsxAiJn5BN+nkbP4mL68c1b+d7G6GMpzM5xsCbRgYv0FiUj1EZw/ML+/Mk5+mOpA9Avo1gfj2EoeBIoX1O2TchQ89KwOS3+7YVyekyXEhSsDftNr4FlIi4XtP1TER7ibb7vTtPXBI4ZwxVEatxipi0g8tpS5RtzhlTtHppQ9Pgd2YH4V2TR5ozaZLLmR4OAHzFkUmomxz5iNW2jbcVY3vVk7aS9/x1KzJhNOkbh1JUJ2HipT5zX/gu7kiTA8EMtoK004mmahCEdVzAhqX3uymbHYNKQbkqugs0V9IG7+KD7VgXrFYUSCp9vcUh6zXkYjrCPgAKXb1hv+fBBZGBHyC4yYkVGX3hetKRVdY9JXDfBVy8W+gVrvhMRAQ==
  template:
    metadata:
      name: immich-secrets
      namespace: immich
