apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: couchdb-secrets
  namespace: obsidian-livesync
  labels:
    app.kubernetes.io/name: obsidian-livesync
    app.kubernetes.io/component: database
spec:
  encryptedData:
    COUCHDB_PASSWORD: AgAmGn6d5FuqtRVGphoVNkYIAxwydj5quDpZTTXOMJ3X6yeXHb3K98TaSvZnIgcWrcSMoUgcLEikL8RuWQ93cpCwNebtIkHqyfmGj4B+uMqpBAxdyIC9fkvrPiwm+6uxR6BQ0ITAj+XCH7f5gALPxe5CUdbwtxu3FPE8uLN9IMAuuJk6Zwe/H6d4L6+CVG+SBetg82obR8J068x297VdfBbN+xMIdgiVFcpyJmg7lH7n4ra0apXrc9/6LxXEnQcsWi3GVkWNopgikX/xOW4FQwplf4IZ/bZOa3Ra08i+3SG+mk1ym3zyk11s/BOTmmxKUz2/pcluyHbiZVeVBLmXe3PdMIZran1VULNKty1iQygdEK3HkZmUXjGL+PIhEB8dwuHImeJt31HJCZHdf+oQthReAidXq+liZSXoYdh1wqD7rWknlM8JgFLLZWY8xRZZpTPgXgxbaBo5ng8PrG4EKh3vY9sjTfuTsGpWTXPtp7064ib5JwOrIeNxCD31enAzY2F8slJ1QQutZ8EuRd3CSXISmoG9drCpkfrA7iWCzxJQiBfJJLKvIMMDH9gQg2uYMfPeZWjOG3CGPjMmbZaGN+UczTq5elrbGQo6o3Yft5yGnBbvEteHWruKHn9G2KJDSOG9bvc45NplN1MD075JAenka5CcVWDS5ivZHEXgYg8saKz71xRSxL9CwMzJwdPUKWw4J24J8Ra54kMyptfxoxAbZDH27naoa5WU9LAkEQjC0g==
    COUCHDB_USER: AgADyqJwF1RLZg3g+X6dCrWb1qsFVBpEMnA7/nK90tAXw/lkPz7f3pLdQrIJm3pgvIlBfYOLG3RQKTlpgF9b7hZ2+unU+6qn3gI56/IGHgRc6S1j/ocmxM0ychsnkopWWsY4UvrdBEnXyr+TPGgif4yEzlPFTq3qjN/cCqjMAW6GHYltoY7xun3xsT1UTQXqL7ww2ffkPhj8KPFUsui7lfHwnFT0uOs0gG3fDrrUR3L/aVQ1cI50/yRx9pM+fJuCKwJd02BPUSWUYXgf3d7ncdCprPCsWex08zXXkPqo+9soU3722dXjkvboX3B4J8pseUJfkcrt9bq95Abq4WcqGzIU1TBiRCdxd+yaNNNWJs/exjztFk5iWvbKEw5SzRroXE2tlyepbYfhQngKOfxC3U1WHoza88Me90UIKVjZf9uXJ7KfxlX/24GJTK1r9wd2rUHFb3Eg4RA0D5Mj/ljcu1W/NKkc0Qh73wyi3YdwgZ+AohjTGdChOudTD0wBw9AYh0rJEiG5RKX1SE162x2qg+vYe7B30HGlVOeYFK+gU6jLtbrqF9jIWlWHmnFCTPMRx7JuybveJDhrImizEchxigWHVoH8xfzYhtj7TBKCxGHgJB8r4aU7x5rE2lW9uUzVaEGgodp7evfrpfXM3jNYQrdCZpKOAI1h886v3qVqleW4HWGqytlhsOPSp5DvfprctfG2o6Y4PQ==
  template:
    metadata:
      name: couchdb-secrets
      namespace: obsidian-livesync
      labels:
        app.kubernetes.io/name: obsidian-livesync
        app.kubernetes.io/component: database
