apiVersion: v1
kind: Service
metadata:
  name: couchdb
  namespace: obsidian-livesync
  labels:
    app.kubernetes.io/name: obsidian-livesync
    app.kubernetes.io/component: database
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 5984
      targetPort: 5984
      protocol: TCP
  selector:
    app.kubernetes.io/name: obsidian-livesync
