apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: nginx
  labels:
    app.kubernetes.io/name: nginx
spec:
  selector:
    app.kubernetes.io/name: nginx
    app.kubernetes.io/instance: nginx-homelab
  ports:
  - name: http
    port: 80
    targetPort: http
