apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: grafana-security-headers
  namespace: kube-system
spec:
  headers:
    stsSeconds: 31536000
    stsIncludeSubdomains: true
    stsPreload: true
    forceSTSHeader: true
    contentTypeNosniff: true
    browserXssFilter: true
    referrerPolicy: "strict-origin-when-cross-origin"
    customResponseHeaders:
      X-Robots-Tag: "noindex, nofollow"
      Permissions-Policy: "camera=(), microphone=(), geolocation=()"
      Content-Security-Policy: "frame-ancestors 'self' https://glance.nicholasshaw.cloud"
