apiVersion: v1
kind: Service
metadata:
  name: kaneo-api
  namespace: kaneo
  labels:
    app.kubernetes.io/name: kaneo-api
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  ports:
    - port: 1337
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: kaneo-api
