---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kaneo-secrets
  namespace: kaneo
spec:
  encryptedData:
    AUTH_SECRET: AgCw+undQZ3YOkDBUUEv4knMYBVUlaotS3qAm+UnMFehG2ezN3avUM3YDe+7/pfmCIWRAqpUy0G3J7YtFhXU37pxFKoxfk20Q2tqoVecRAWaEVUJM42oYNchazEVwHyGiEz1AKRkIx7cFXlHagXJfZQN7jGHGKV32FvKxfJ9vkHv6Mpk93cFjHwl15QBSw0YeWm46oaSIp7k/TnFS0P2qlKetGpkIKciDGrJrwiYSrQqS/RrKeI7i/VyTPdCxGnexpXx1jiNHTD++bFNct5Nz6po8pXBkHFiol6WYwIfHQZa8I/HpPP9/eQ7FpnPh7NAmViwM4n2HiLzaVX8jypXumNuS6LjoL2/t6Y73W0FxT/hE4JL6ErSZ5RTaWj3g0yOBh78PhH6yW6QmHp31uKSrJBuOg0qHY7wK3XNUIE7nrFheparVyrqpi5b//6OG28WD2jLN7DTb1wOLeJ8sntHOeHZAi15Me1XiwrOJt4gXy7jpiNmj6nHzk2tlDOPCdZ4AuYGzczX0gkeh0G60/6SkrqC6eOij4DURylSL/cMokKLo9MVuDjlN5vB9pi/72Y2SxacTibsKRZSKpyRlDrakCs5u/vYbfh0TfylqGjpbK6vF6Tu44qyT0fgphPgltfVVSOlaBOOfYMp2OU4YWGjYysliRvsVcJE9931Ly7Gxc64aOodm+yZ/bJwyw7mXCtzGfvu8yz7sIR1TzgbpN2RZKvhmF36Z5EUrdkiWpsk/TLpyL9zK60tl4IjR5jAaIX9OizEHkFFRtevmDCy14RwZFTa
    POSTGRES_PASSWORD: AgCz5lNi9DSoM+BQC9uyu/7IiGuBuE3NA/OavbzIk8kGrkObbNZcBa/e3qIuyDBMGwLH6IxtqdHQzA079+YvkVBeLQqhfHRt69UKFeGD/tLTCKt1frB289N6TqmG+bKNdTdUcYH0Qa88h9NUbet/76aCSg9sEIfogGTT2sSGNrKQ32/C+3HaV4UT3WbNHKJzQrTc2sTGkDpsmKdJLX41dPo3xk7IN/yIYf3wm7BKMq5qHjhYXNRo6sYJkQLpQVFvuCnCkh8BiSFkBWMfLXubK22vabVv+HKObpbdtK6KtVRK+yqYWQfCSRE2rIjvTvimLmGupFkaynCcn6q7leDlIW9atVt2aU1zK9O1mFq3l+ZvhzjmCDO5QgoDCDaCza5epQyAmwr6r2Rp2QCKAXjh1fo24BGzf0MkFL27TZLvMGUC3XvWXUxbjiTjCbYq2hJSpJ7TeYhr8w81oxPuTGW4XcsaCYoU4rB7tJqyz81i2DH4avA1aJDi11O9F0K60+4WRlrGiq7c6iRxlAz0UGEVaY7z6RFRnckvmz/zBh1l4JZPWU4DEVnuI4l5WBNl9Ly6AFFcbBJVUu9ULqcJuzuFUQPP1upsmcX4y4LImHZc32YF0utWQ8LL3VeIALFd9VPhf7fc714IX6BXYTyeDfrS1ZF417OC0kay4ZgR5dYGzurs/2EFi19a3qPb6t8ttwbovSU20+LXx4Oza/THpTq8lzFpJjaI7Mx8bM8s0IG+0r9Jhw==
  template:
    metadata:
      name: kaneo-secrets
      namespace: kaneo
