apiVersion: v1
kind: Service
metadata:
  name: kaneo-web
  namespace: kaneo
  labels:
    app.kubernetes.io/name: kaneo-web
    app.kubernetes.io/component: web
spec:
  type: ClusterIP
  ports:
    - port: 5173
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: kaneo-web
