---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-secret
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgBaKeq77OlLXR4CmyGgjuXc/ZgMmPlhBDXluGatlcalapAaU6j+dvSKDP/gHOMWE3CWZskwtnKx8djhXNfp9QcyQrhmqEIoHvnZRRZsDM5Qt/42h9NTzHMbABoVqLUuoQZrjG4TadpTWzYfGq3kgq6DKn/b1O/Do0AdCA+n+BRS3b2SAFpwnnLAWEqGc4KBiZc5F1qaZIv7FPqjgUsjM1jT2s421nRPA0LMiZH3DAYNHwR16txESYyqacVVsnyDTQnhp7rgKg0h4jw6zLc8Q3PLqWNcCO+dbEkfvXBbQuCLhBAxoz9hCoGJ2F4Zn943ApU7Iq0jog9QZXNswICSReeaC+e3ZRkV129oa18S/bIpjvl9GNpgYFse46T5A5v3kCiJZVTC74YkCSj+vjXw4UO3UEhb3E09nRJJWuKIFwJWAWTX0+laO6oeg+eVupBidOjBMAFgUhsqRHBAxbMSCiL7MyGywlUO5yzEdyPkICHdWtiwn10i5wuJ7UVbM/k31kl6o+GTm/J+cq12cA6fpSFBO+mdRRVm514FWb1rxMZ6E3Pq47F5q/gAPtYwWxXFnxHMu5PrNouVFXqAzF0CpHQPFkf8wyubVRVBcEllw/EzIhEIp4w8MWCkAtnUDOKK4kappXC/CsV48SbNtTdcAVF3FqnnMa5wd6AEit6xhUipQgxlU17A8D6JHXXhNFqpAutRYOYzmaS03lXAKMtZ7jviwBn27WfCPwxaLuL5v6dozw==
    admin-user: AgAAChvfBKIbbXklXa86NPrnUyRiGU8pAUxEuZT6s9iewK33fK4LruIKt/dHKyxMjQRmI/po1iA7PpI6q8t5qSYpj+fIf5XAc4bXy2IogSFu4j2oL6CidARCYSj44hzzs0FHlgwzgdSUuKz0KtBUtsrqxJxqUACJtmvZtJwzlI+n6g43Z6ypHMs340vMXPWJrFuQuyQcZF9Te3M87fi7apnCNJqXubPr7IWPhS2nLEZrW5HJTv28HcXKQZF+MH14qcic9Qkn8GGObMkFKpVRwAUiQCQtcoiwNjRZsP5gqwQe85xFcfcNd0H5GoGPAw07CsEG7Yqfxm9LwZP/rmyVdYNYyEWZD5Ar/goEagT0HfMf3Gqx6NQd/ZrTCX+psoI25ovDeoq7nYafc2/yA8zEHTWnHyoArgSBzsVwQbF++MOyMjdkN3CMCMbDZZkDKgI4ahngCC6nJ10HrozGBDYvk1ULWFz83F5X9tyaKZ86BNTj1il1N1o77XCalQUIdNR50sG47bqPYdo88fg/kcjvXXgcx/vc5n6qr/rvTtmpOjMFY/isyvS2t+9e0Wh3+JxG82GgF64jzQZiGMfyYcbw144rXiSYUTNDfSZSJm/PbWXrYmjAj6Rv1+V4TKRUE6lK/sOdiro42NiSeFpYOnIK/rbG1BSoopQwcfQbdLq13/JATuhn1fR4LMEkci3dyEFXUvRFYBxwAA==
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
