---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-secret
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgAUfgRqoFANzF1K0hsWQ+8tAGKC51+n0XqFDtNZ4qnUR2f+ZQeJVxqtLNkleYWfu/CaJ8GdL/mImhbbZdGMnJSb31qiCPeco/OpfU5nFYITBpMv32XtWz1GRifCVXQEra9HbXh0i3yl4HVUw2zjpgzDeTjskwQjg0sXWgbir0EPV2teZB/Ch5KNzZqODIBVV/2vsESQ8O17yF89D+8JG4+OlUk5xud3+zbagP29v6Lku76V8PqMwU4S4azg+4D9bX0D/Ct5VD8WtBFv6oVYPc0HxlAAe4KE6JtJp99iOcLVCnlrACr//TnYz/lhvkiVKKsuGnvTAZK0+DU3FDWh36Moi5SrSc2d0Rd13fzJLV0ZPojivLaWRiRsbnttNf3/0UQW1Z7P2G2mvhfRvzmlSh6Uk+TN8mmN5dgVvbPlz6omJsu+jniLF0tluqcpqmnYySjWOcQFgqRwgS6zpXz2TWKcwjYHSVabrP9M0L8t4vAjRZJ/r+mLAzhrl3/VhI1u0XfSrvr8Il8MUhMVSYHliilqOZQxBPYifvRXyEdUlRq+n3hVJNvthU8UGaLPHa2HdIAb63rQpBpJaA7NfIhm447UT8TyR5PxUICzJr4XAFrHrIFSPsHnE7uqz1BcVSgdI8Nipzmils5vcfuGoc1502dKd+EQAeJkLx4YV7LmOVTsH5BK+yQm8KfSwvgbcFYAJ4v8sc1zCvU44yuU00RnJosgAjxd7RJGDEjRXwlGYTDqMw==
  template:
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
