apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: postiz
  namespace: postiz
  labels:
    app.kubernetes.io/name: postiz
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.middlewares: kube-system-security-headers@kubernetescrd,kube-system-rate-limit@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - postiz.nicholasshaw.cloud
  rules:
    - host: postiz.nicholasshaw.cloud
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: postiz
                port:
                  number: 5000
