apiVersion: v1
kind: Service
metadata:
  name: postiz-redis
  namespace: postiz
  labels:
    app.kubernetes.io/name: postiz-redis
    app.kubernetes.io/component: cache
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: redis
      protocol: TCP
      name: redis
  selector:
    app.kubernetes.io/name: postiz-redis
