apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postiz-uploads
  namespace: postiz
  labels:
    app.kubernetes.io/name: postiz
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
