apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nicholasshaw-cloud-wildcard
  namespace: cert-manager
spec:
  secretName: nicholasshaw-cloud-wildcard-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "*.nicholasshaw.cloud"
  dnsNames:
    - "nicholasshaw.cloud"
    - "*.nicholasshaw.cloud"
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: ""
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "kube-system,argocd,longhorn-system"
