apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: productivity
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  source:
    repoURL: https://github.com/nshaw928/homelab.git
    targetRevision: main
    path: apps/productivity
  
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true