apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: glance

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

configMapGenerator:
  - name: glance
    files:
      - config/glance.yml
      - config/home.yml
      - config/media.yml
  - name: glance-feeds
    files:
      - config/bookmarks.yml
      - config/feeds/reddit.yml
      - config/feeds/rss.yml

generatorOptions:
  disableNameSuffixHash: true
