apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: immich
  namespace: argocd
  annotations:
    argocd.argoproj.io/compare-options: ServerSideDiff=true
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://immich-app.github.io/immich-charts
    chart: immich
    targetRevision: 0.10.3
    helm:
      values: |
        immich:
          persistence:
            library:
              existingClaim: immich-library

        server:
          enabled: true
          ingress:
            main:
              enabled: true
              annotations:
                traefik.ingress.kubernetes.io/router.entrypoints: websecure
                traefik.ingress.kubernetes.io/router.tls: "true"
              hosts:
                - host: immich.nicholasshaw.cloud
                  paths:
                    - path: "/"
                      service:
                        identifier: main
              tls:
                - hosts:
                    - immich.nicholasshaw.cloud

        env:
          DB_HOSTNAME: immich-postgres
          DB_PORT: "5432"
          DB_USERNAME: immich
          DB_DATABASE_NAME: immich
          DB_PASSWORD:
            valueFrom:
              secretKeyRef:
                name: immich-secrets
                key: DB_PASSWORD

        image:
          tag: v2.5.6

        machine-learning:
          enabled: true
          persistence:
            cache:
              enabled: true
              size: 10Gi
              type: persistentVolumeClaim
              storageClass: longhorn
              accessMode: ReadWriteOnce

        valkey:
          enabled: true
          persistence:
            data:
              enabled: true
              size: 1Gi
              type: persistentVolumeClaim
              storageClass: longhorn
              accessMode: ReadWriteOnce
  destination:
    server: https://kubernetes.default.svc
    namespace: immich
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
