apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karakeep-secrets
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://gitea.nicholasshaw.cloud/nick/homelab.git
    targetRevision: main
    path: apps/karakeep
  destination:
    server: https://kubernetes.default.svc
    namespace: karakeep
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
