---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: linkwarden-secrets
  namespace: linkwarden
spec:
  encryptedData:
    NEXTAUTH_SECRET: AgBqCrQV7gI6Aam9gpaThTbGTwxByLSQdW6DKbvIAJO1Vg39uPXSSHG8OCdAoZBuXJ77tlq/2BShnt4uoZRxt2oNNSOLyp7HHmNJ7XVDDPVhPr+zyFu0ArVbQL8LRnExPmChQm8BXTa8l5IghOt36H5udBSrMgCoRz8t0d3EO7E8bmDqDalU2pjLYomA2BLH76lZ8MYg1QFnPDJ0bbGwmKYFM2HRM6broRKDLcCRcKd447yXrVaXgKv1kSFjDBZZP78AGaxv8EbA33fp5h0n48U6FK51aJku+6WWNwsqcQcxlkUHfZ6wI5v6x4kLGQLNacUALqJCDjZzdBeF6oNlgtSm4fvFFtSbNBvqwGGEvP2VdtNfgO0eqcivdL1jC/99LxXFTYyMxw7aIoK6s4M0AzIbKO+GwqamIDR8stjUBbounhkejfj0euS23M3P5GaabWGiN58FmJdqrNCDKpb80giftlMD7zT1oTd7gUyJHSrL3biHxSyMB9rga5c4rAavnIQ17HgqO98caI1dgmqv6qlxOsPOMQlw23E6v32hGxHT8fG0G7bhmG7mcl4mZxD95bSuISWfPWdF4aeps+XlyT9vogXiyeGr9V2GeQ/k5jAJUIDBYmEv/0k0/VagIzJYuwXl9Z+qS95ibra7I4FMw9seVghfmvtoerL/O5AqEvQRi9ELkyAjlX14jNr/Y/b+YGvOSkQT/JDF8/Iz/JHEvGWMV2SJ/qSgdr+yBDIJwA2B2o1F03nghXlH1Bm4cw==
    POSTGRES_PASSWORD: AgBR7BIqrjXsoirT94mUfH1dy713AMxlB4tvzcsFUX90R5V+QamO9I3yZ2JWX7G9KztH/kFXv8zLLqVQKaZfeVf1AoRpvQysOe2pi0d+EVjEnXO+BQijT8MOuhkLNJVu3Rl+VmN5i/KcWLztKeDgZelRV1ceSDOGUOiUfllnCKFZ62lxW6XJkWD06HZFGwdDuRc/vp+D9Im1E5/f6zfgFR9JPbvrbI+5F/APabOkg0mmG1KdbFHYKYzyZX6PvVOP23G3vzYvUCzR3mLFV/RcS7kK8rqt2YAExto3/SOWWK75TdEDb9Jd2bXleyXKgB3lU1EStKduiWYLlrQdCCaikfi8A9vgVBRAS1C8YFlZCQ4gBj8iA4UMkO93s3a2ZmTx51HInG0h/UCnsvNvR3oyPveTL1q7vEzKioD8V7s8tY33zal3W6XmvV0uRjaGnCBanJJbopMBM9SaVf8a9POywTk66xuiv91mngrXc6uSZ+zFa2BDBaPahAX9uBCnPaEaVMswmx0AVC8ahrplO9brAeZEm7xhWzfl82s1lI4XJyrEa7dfUiZ2/zlwA+6wOdBGZFUAhFwlSg9PZOB2/HeJdAnNgzlqSA44bHCC0rHOekd6ySmvsitlb+hWtawmrSoE5HuHDR38Dbcx7aUTebb6D7QQduMzIEX/6oyfw9mzn6UGkmmRdUr77tS+Vdk74ZJU1LSOZ0BlYAEXgPmhMiU4dSxNPaX98YozdtxO5Q02BDJG6w==
  template:
    metadata:
      name: linkwarden-secrets
      namespace: linkwarden
