apiVersion: v1
kind: Service
metadata:
  name: stoat-api
  namespace: stoat
  labels:
    app.kubernetes.io/name: stoat-api
spec:
  type: ClusterIP
  ports:
    - port: 14702
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: stoat-api
