apiVersion: v1
kind: ConfigMap
metadata:
  name: stoat-caddyfile
  namespace: stoat
  labels:
    app.kubernetes.io/name: stoat-caddy
data:
  Caddyfile: |
    {
      auto_https off
    }

    :8080 {
      handle /ws {
        reverse_proxy stoat-events:14703
      }

      handle_path /api/* {
        reverse_proxy stoat-api:14702
      }

      handle_path /autumn/* {
        reverse_proxy stoat-autumn:14704
      }

      handle_path /january/* {
        reverse_proxy stoat-january:14705
      }

      handle_path /gifbox/* {
        reverse_proxy stoat-gifbox:14706
      }

      handle {
        reverse_proxy stoat-web:5000
      }
    }
