apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stoat
  namespace: stoat
  labels:
    app.kubernetes.io/name: stoat
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.middlewares: kube-system-security-headers@kubernetescrd,kube-system-rate-limit@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - stoat.nicholasshaw.cloud
  rules:
    - host: stoat.nicholasshaw.cloud
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: stoat-caddy
                port:
                  number: 80
